# Generated by Django 4.1.7 on 2023-04-23 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_gender_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamarea',
            name='manager',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='position', to='users.position'),
            preserve_default=False,
        ),
    ]
