# Generated by Django 4.1.7 on 2023-04-23 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_teamarea_manager_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='area_associated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_area_of_position', to='users.teamarea'),
        ),
    ]
