# Generated by Django 4.1.7 on 2023-04-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='position', to='users.position'),
            preserve_default=False,
        ),
    ]
