# Generated by Django 4.1.7 on 2024-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamarea',
            name='color_code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
