# Generated by Django 4.1.7 on 2024-02-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_teamarea_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_position', to='users.position'),
        ),
    ]
