# Generated by Django 4.1.7 on 2024-01-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicaxis',
            name='intentionality',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
