# Generated by Django 4.1.5 on 2023-03-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField()),
                ('area_involved', models.ManyToManyField(blank=True, related_name='area_involved', to='users.teamarea')),
                ('area_responsible', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='area_responsible', to='users.teamarea')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
