# Generated by Django 4.1.7 on 2024-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0013_activity_is_main_activity'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='metric_associated',
            field=models.ManyToManyField(blank=True, related_name='event_metrics', to='metrics.metric'),
        ),
    ]
