# Generated by Django 4.1.7 on 2024-02-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_event_activity_associated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='activity_associated',
        ),
    ]
