# Generated by Django 4.1.7 on 2024-02-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_activity_area_responsible'),
        ('agenda', '0004_remove_event_activity_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_activity', to='metrics.activity'),
        ),
    ]
