# Generated by Django 4.1.5 on 2023-03-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('strategy', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaActivated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=420, verbose_name='Name of the area activated')),
                ('contact', models.TextField(blank=True, max_length=420)),
            ],
            options={
                'verbose_name': 'Area activated',
                'verbose_name_plural': 'Areas activated',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=420)),
            ],
            options={
                'verbose_name': 'Editor',
                'verbose_name_plural': 'Editors',
            },
        ),
        migrations.CreateModel(
            name='EvaluationObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
            ],
            options={
                'verbose_name': 'Evaluation objective',
                'verbose_name_plural': 'Evaluation objectives',
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Funding',
                'verbose_name_plural': 'Fundings',
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
            ],
            options={
                'verbose_name': 'Learning area',
                'verbose_name_plural': 'Learning areas',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
            ],
            options={
                'verbose_name': 'Organizer',
                'verbose_name_plural': 'Organizers',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='StrategicLearningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
                ('learning_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategic_question', to='report.learningarea')),
            ],
            options={
                'verbose_name': 'Strategic learning question',
                'verbose_name_plural': 'Strategic learning questions',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('activity_other', models.TextField(blank=True, default='', max_length=420)),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=420)),
                ('links', models.TextField(max_length=10000)),
                ('public_communication', models.TextField(max_length=10000)),
                ('should_be_on_meta', models.BooleanField()),
                ('quantity_of_participants', models.IntegerField(blank=True, default=0, null=True)),
                ('resources', models.IntegerField(blank=True, default=0, null=True)),
                ('feedbacks', models.IntegerField(blank=True, default=0, null=True)),
                ('wikipedia_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikipedia_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('commons_created', models.IntegerField(blank=True, default=0, null=True)),
                ('commons_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wikidata_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikidata_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wikiversity_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikiversity_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wikibooks_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikibooks_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wikisource_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikisource_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wikinews_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikinews_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wikiquote_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikiquote_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wiktionary_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wiktionary_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wikivoyage_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikivoyage_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('wikispecies_created', models.IntegerField(blank=True, default=0, null=True)),
                ('wikispecies_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('metawiki_created', models.IntegerField(blank=True, default=0, null=True)),
                ('metawiki_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('mediawiki_created', models.IntegerField(blank=True, default=0, null=True)),
                ('mediawiki_edited', models.IntegerField(blank=True, default=0, null=True)),
                ('learning', models.TextField(blank=True, max_length=4200)),
                ('activity_associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activity_associated', to='metrics.activity')),
                ('area_activated', models.ManyToManyField(related_name='area_activated', to='report.areaactivated')),
                ('area_responsible', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responsible', to='users.teamarea')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_reporting', to='users.userprofile')),
                ('directions_related', models.ManyToManyField(blank=True, related_name='direction_related', to='strategy.direction')),
                ('editors', models.ManyToManyField(blank=True, related_name='editors', to='report.editor')),
                ('funding_associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='funding_associated', to='report.funding')),
                ('learning_questions_related', models.ManyToManyField(blank=True, related_name='strategic_learning_question_related', to='report.strategiclearningquestion')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_modifying', to='users.userprofile')),
                ('organizers', models.ManyToManyField(blank=True, related_name='organizers', to='report.organizer')),
                ('partners_activated', models.ManyToManyField(blank=True, related_name='partners', to='report.partner')),
                ('technologies_used', models.ManyToManyField(blank=True, related_name='tecnologies', to='report.technology')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.AddField(
            model_name='organizer',
            name='institution',
            field=models.ManyToManyField(related_name='organizer_institution', to='report.partner'),
        ),
        migrations.CreateModel(
            name='EvaluationObjectiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=4200, null=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='report.evaluationobjective')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_objective_answer', to='report.report')),
            ],
            options={
                'verbose_name': 'Evaluation objective answer',
                'verbose_name_plural': 'Evaluation objective answers',
            },
        ),
        migrations.AddField(
            model_name='evaluationobjective',
            name='learning_area_of_objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_objective', to='report.learningarea'),
        ),
    ]
