# Generated by Django 4.1.7 on 2023-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaactivated',
            name='contact',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
    ]
