# Generated by Django 4.1.7 on 2023-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_rename_quantity_of_participants_report_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='learning',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
