# Generated by Django 4.1.7 on 2023-03-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='area_activated',
            field=models.ManyToManyField(null=True, related_name='area_activated', to='report.areaactivated'),
        ),
    ]
