# Generated by Django 4.1.7 on 2023-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_area_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='area_activated',
            field=models.ManyToManyField(blank=True, related_name='area_activated', to='report.areaactivated'),
        ),
    ]
