# Generated by Django 4.1.7 on 2023-03-18 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_area_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='learning',
            field=models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(500)]),
        ),
    ]
