# Generated by Django 4.1.7 on 2023-03-18 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('strategy', '0001_initial'),
        ('report', '0007_alter_report_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activity_associated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='activity_associated', to='metrics.activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='directions_related',
            field=models.ManyToManyField(related_name='direction_related', to='strategy.direction'),
        ),
        migrations.AlterField(
            model_name='report',
            name='learning',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='learning_questions_related',
            field=models.ManyToManyField(related_name='strategic_learning_question_related', to='report.strategiclearningquestion'),
        ),
    ]
