# Generated by Django 4.1.7 on 2023-04-22 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('report', '0009_alter_report_activity_associated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activity_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activity_associated', to='metrics.activity'),
        ),
        migrations.AlterField(
            model_name='report',
            name='activity_other',
            field=models.TextField(blank=True, default='', max_length=420),
        ),
    ]
