# Generated by Django 4.1.7 on 2023-04-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('report', '0010_alter_report_activity_associated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_other', models.TextField(blank=True, default='', max_length=420)),
                ('activity_associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activity_associated_new', to='metrics.activity')),
            ],
        ),
    ]
