# Generated by Django 4.1.7 on 2023-04-23 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('report', '0011_newreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activity_associated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='activity_associated', to='metrics.activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='area_activated',
            field=models.ManyToManyField(blank=True, related_name='area_activated', to='report.areaactivated'),
        ),
        migrations.AlterField(
            model_name='report',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors', to='report.editor'),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedbacks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizers', to='report.organizer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='participants',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='partners_activated',
            field=models.ManyToManyField(blank=True, related_name='partners', to='report.partner'),
        ),
        migrations.AlterField(
            model_name='report',
            name='resources',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, related_name='tecnologies', to='report.technology'),
        ),
        migrations.DeleteModel(
            name='NewReport',
        ),
    ]
