# Generated by Django 4.1.7 on 2023-04-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_report_activity_associated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='public_communication',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
