# Generated by Django 4.1.7 on 2023-04-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_delete_evaluationobjectiveanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategiclearningquestion',
            name='learning_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strategic_question', to='report.learningarea'),
            preserve_default=False,
        ),
    ]
