# Generated by Django 4.1.7 on 2023-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_alter_strategiclearningquestion_learning_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='funding_associated',
        ),
        migrations.AddField(
            model_name='report',
            name='funding_associated',
            field=models.ManyToManyField(blank=True, related_name='funding_associated', to='report.funding'),
        ),
    ]
