# Generated by Django 4.1.7 on 2023-04-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_project_metric_project'),
        ('report', '0018_remove_report_funding_associated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='project_related', to='metrics.project'),
            preserve_default=False,
        ),
    ]
