# Generated by Django 4.1.7 on 2023-05-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_project_status_alter_metric_project'),
        ('report', '0020_alter_report_activity_associated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activity_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activity_associated', to='metrics.activity'),
        ),
    ]
