# Generated by Django 4.1.7 on 2023-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_alter_report_activity_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='retained',
            field=models.BooleanField(default=False),
        ),
    ]
