# Generated by Django 4.1.7 on 2023-06-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_area_project'),
        ('report', '0022_editor_retained'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='metrics_related',
            field=models.ManyToManyField(related_name='metrics_related', to='metrics.metric'),
        ),
    ]
