# Generated by Django 4.1.7 on 2023-06-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_area_project'),
        ('report', '0023_report_metrics_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='metrics_related',
            field=models.ManyToManyField(blank=True, related_name='metrics_related', to='metrics.metric'),
        ),
    ]
