# Generated by Django 4.1.7 on 2023-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_alter_report_metrics_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='account_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
