# Generated by Django 4.1.7 on 2023-09-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_alter_editor_account_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='retained',
            field=models.BooleanField(default=False),
        ),
    ]
