# Generated by Django 4.1.7 on 2023-09-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_organizer_retained'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='number_of_people_reached_through_social_media',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
