# Generated by Django 4.1.7 on 2024-01-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_remove_report_number_of_community_communications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationreport',
            old_name='number_of_partnerships',
            new_name='number_of_partnerships_activated',
        ),
        migrations.RenameField(
            model_name='operationreport',
            old_name='resources',
            new_name='number_of_resources',
        ),
    ]
