# Generated by Django 4.1.7 on 2024-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0032_rename_number_of_partnerships_operationreport_number_of_partnerships_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationreport',
            name='number_of_new_partnerships',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
