# Generated by Django 4.1.7 on 2024-02-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_operationreport_number_of_new_partnerships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='learning',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
