# Generated by Django 4.1.7 on 2024-02-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_activity_area_responsible'),
        ('report', '0034_alter_report_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activity_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='report_activity', to='metrics.activity'),
        ),
    ]
