# Generated by Django 5.0.6 on 2024-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0035_alter_report_activity_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reference_text',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
