# Generated by Django 5.1.1 on 2024-11-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_report_private_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='partial_report',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
