# Generated by Django 5.1.1 on 2025-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0038_report_partial_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='donors',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='submissions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
