# Generated by Django 4.1.5 on 2023-03-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
                ('code', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
                ('related_axis', models.ManyToManyField(related_name='areas', to='strategy.strategicaxis')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='metrics.area')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
                ('wikipedia_created', models.IntegerField(default=0, null=True)),
                ('wikipedia_edited', models.IntegerField(default=0, null=True)),
                ('commons_created', models.IntegerField(default=0, null=True)),
                ('commons_edited', models.IntegerField(default=0, null=True)),
                ('wikidata_created', models.IntegerField(default=0, null=True)),
                ('wikidata_edited', models.IntegerField(default=0, null=True)),
                ('wikiversity_created', models.IntegerField(default=0, null=True)),
                ('wikiversity_edited', models.IntegerField(default=0, null=True)),
                ('wikibooks_created', models.IntegerField(default=0, null=True)),
                ('wikibooks_edited', models.IntegerField(default=0, null=True)),
                ('wikisource_created', models.IntegerField(default=0, null=True)),
                ('wikisource_edited', models.IntegerField(default=0, null=True)),
                ('wikinews_created', models.IntegerField(default=0, null=True)),
                ('wikinews_edited', models.IntegerField(default=0, null=True)),
                ('wikiquote_created', models.IntegerField(default=0, null=True)),
                ('wikiquote_edited', models.IntegerField(default=0, null=True)),
                ('wiktionary_created', models.IntegerField(default=0, null=True)),
                ('wiktionary_edited', models.IntegerField(default=0, null=True)),
                ('wikivoyage_created', models.IntegerField(default=0, null=True)),
                ('wikivoyage_edited', models.IntegerField(default=0, null=True)),
                ('wikispecies_created', models.IntegerField(default=0, null=True)),
                ('wikispecies_edited', models.IntegerField(default=0, null=True)),
                ('metawiki_created', models.IntegerField(default=0, null=True)),
                ('metawiki_edited', models.IntegerField(default=0, null=True)),
                ('mediawiki_created', models.IntegerField(default=0, null=True)),
                ('mediawiki_edited', models.IntegerField(default=0, null=True)),
                ('number_of_editors', models.IntegerField(default=0, null=True)),
                ('number_of_participants', models.IntegerField(default=0, null=True)),
                ('number_of_partnerships', models.IntegerField(default=0, null=True)),
                ('number_of_resources', models.IntegerField(default=0, null=True)),
                ('number_of_feedbacks', models.IntegerField(default=0, null=True)),
                ('number_of_events', models.IntegerField(default=0, null=True)),
                ('other_type', models.CharField(blank=True, max_length=420, null=True)),
                ('observation', models.CharField(blank=True, max_length=420, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metrics.activity')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activities', to='metrics.area'),
        ),
    ]
