# Generated by Django 4.1.7 on 2023-04-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='number_of_organizers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
