# Generated by Django 4.1.7 on 2023-05-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_project_metric_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project_associated', to='metrics.project'),
        ),
    ]
