# Generated by Django 4.1.7 on 2023-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_metric_number_of_editors_retained'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='number_of_new_editors',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
