# Generated by Django 4.1.7 on 2024-01-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_metric_boolean_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='active',
        ),
        migrations.AddField(
            model_name='project',
            name='current_poa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='main_funding',
            field=models.BooleanField(default=False),
        ),
    ]
