# Generated by Django 4.1.7 on 2024-01-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_rename_status_project_active_project_current_poa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='number_of_partnerships',
            new_name='number_of_partnerships_activated',
        ),
        migrations.AddField(
            model_name='metric',
            name='number_of_community_communications',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='number_of_mentions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='number_of_new_followers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='number_of_new_partnerships',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
