# Generated by Django 4.1.7 on 2024-01-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_rename_number_of_partnerships_metric_number_of_partnerships_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='is_operation',
            field=models.BooleanField(default=False),
        ),
    ]
