# Generated by Django 4.1.7 on 2024-01-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0012_metric_is_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_main_activity',
            field=models.BooleanField(default=False),
        ),
    ]
