# Generated by Django 5.1.1 on 2024-12-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_activity_area_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='text_en',
            field=models.CharField(blank=True, default='', max_length=420),
        ),
    ]
