# Generated by Django 5.1.1 on 2025-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0015_metric_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='number_of_donors',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='number_of_submissions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
