# Generated by Django 4.1.7 on 2023-03-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_userprofile_wiki_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(max_length=500)),
                ('date_of_report', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('1', 'To do'), ('2', 'In progress'), ('3', 'Testing'), ('4', 'Done')], default='1', max_length=1)),
                ('type_of_bug', models.CharField(choices=[('1', 'Error'), ('2', 'Improvement request'), ('3', 'New feature request'), ('4', 'Question or clarification')], default='1', max_length=1)),
                ('observation', models.TextField(blank=True, max_length=500, null=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reporter', to='users.userprofile')),
            ],
        ),
    ]
