# Generated by Django 4.1.7 on 2023-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_alter_bug_reporter_alter_bug_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Update date'),
        ),
    ]
