# Generated by Django 4.1.7 on 2023-04-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_gender'),
        ('bug', '0007_remove_bug_observation_alter_bug_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='reporter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='reporter', to='users.userprofile'),
        ),
    ]
