# Generated by Django 4.1.7 on 2023-05-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0008_alter_bug_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('1', 'To do'), ('2', 'In progress'), ('3', 'Testing'), ('4', 'Done'), ('5', 'Canceled')], default='1', max_length=1, verbose_name='Status'),
        ),
    ]
