# Generated by Django 5.0.6 on 2024-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0009_alter_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('0', 'To do'), ('1', 'In evaluation'), ('2', 'In progress'), ('3', 'Testing'), ('4', 'Done'), ('5', 'Canceled')], default='1', max_length=1, verbose_name='Status'),
        ),
    ]
